"""empty message

Revision ID: 04d8cb5c94e5
Revises: 2b11266a2332
Create Date: 2017-03-06 20:36:04.960178

"""

# revision identifiers, used by Alembic.
revision = '04d8cb5c94e5'
down_revision = '2b11266a2332'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('image', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('myprofile', 'image')
    ### end Alembic commands ###
